name: teaching_routine_manager
description: A digital teaching log and routine manager.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # লোকাল ডেটাবেস সেভ রাখার জন্য শুধু এটিই দরকার
  shared_preferences: ^2.2.2 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
